import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      sm: "600px",
      md: "960px",
      lg: "1280px",
      xl: "1536px",
      "2xl": "1920px",
    },
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        border: "var(--border)",
        input: "var(--input)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        surface: {
          DEFAULT: "var(--surface)",
          muted: "var(--surface-muted)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        "purple-dark": "var(--zulu-purple-dark)",
        status: {
          success: "var(--status-success)",
          error: "var(--status-error)",
          warning: "var(--status-warning)",
          info: "var(--status-info)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          900: "var(--color-primary-900)",
          800: "var(--color-primary-800)",
          700: "var(--color-primary-700)",
          600: "var(--color-primary-600)",
          500: "var(--color-primary-500)",
          400: "var(--color-primary-400)",
          300: "var(--color-primary-300)",
          200: "var(--color-primary-200)",
          100: "var(--color-primary-100)",
          50: "var(--color-primary-50)",
          10: "var(--color-primary-10)",
        },
        secondary: {
          900: "var(--color-secondary-900)",
          800: "var(--color-secondary-800)",
          700: "var(--color-secondary-700)",
          600: "var(--color-secondary-600)",
          500: "var(--color-secondary-500)",
          400: "var(--color-secondary-400)",
          300: "var(--color-secondary-300)",
          200: "var(--color-secondary-200)",
          100: "var(--color-secondary-100)",
          50: "var(--color-secondary-50)",
          10: "var(--color-secondary-10)",
        },
        tertiary: {
          900: "var(--color-tertiary-900)",
          800: "var(--color-tertiary-800)",
          700: "var(--color-tertiary-700)",
          600: "var(--color-tertiary-600)",
          500: "var(--color-tertiary-500)",
          400: "var(--color-tertiary-400)",
          300: "var(--color-tertiary-300)",
          200: "var(--color-tertiary-200)",
          100: "var(--color-tertiary-100)",
          50: "var(--color-tertiary-50)",
        },
        error: {
          900: "var(--color-error-900)",
          800: "var(--color-error-800)",
          700: "var(--color-error-700)",
          600: "var(--color-error-600)",
          500: "var(--color-error-500)",
          400: "var(--color-error-400)",
          300: "var(--color-error-300)",
          200: "var(--color-error-200)",
          100: "var(--color-error-100)",
          50: "var(--color-error-50)",
        },
        success: {
          900: "var(--color-success-900)",
          800: "var(--color-success-800)",
          700: "var(--color-success-700)",
          600: "var(--color-success-600)",
          500: "var(--color-success-500)",
          400: "var(--color-success-400)",
          300: "var(--color-success-300)",
          200: "var(--color-success-200)",
          100: "var(--color-success-100)",
          50: "var(--color-success-50)",
        },
        info: {
          900: "var(--color-info-900)",
          800: "var(--color-info-800)",
          700: "var(--color-info-700)",
          600: "var(--color-info-600)",
          500: "var(--color-info-500)",
          400: "var(--color-info-400)",
          300: "var(--color-info-300)",
          200: "var(--color-info-200)",
          100: "var(--color-info-100)",
          50: "var(--color-info-50)",
        },
        warning: {
          900: "var(--color-warning-900)",
          800: "var(--color-warning-800)",
          700: "var(--color-warning-700)",
          600: "var(--color-warning-600)",
          500: "var(--color-warning-500)",
          400: "var(--color-warning-400)",
          300: "var(--color-warning-300)",
          200: "var(--color-warning-200)",
          100: "var(--color-warning-100)",
          50: "var(--color-warning-50)",
        },
        zulu: {
          navy: "var(--text-t9)",
          placeholder: "var(--input-placeholder)",
          gray: {
            DEFAULT: "var(--text-primary)",
            light: "var(--text-t6)",
            muted: "var(--text-typography-t6)",
            border: "var(--border-default)",
          },
        },
        /** Figma text palette (Text color/T1…T9) — use e.g. text-fg-t8 */
        "fg-t1": "var(--text-t1)",
        "fg-t2": "var(--text-t2)",
        "fg-t3": "var(--text-t3)",
        "fg-t4": "var(--text-t4)",
        "fg-t6": "var(--text-t6)",
        "fg-t7": "var(--text-t7)",
        "fg-t8": "var(--text-t8)",
        "fg-t9": "var(--text-t9)",
        "fg-t11": "var(--text-t11)",
        /** Typography specimen (node 1:22396) */
        "typography-t8": "var(--text-typography-t8)",
        "typography-t6": "var(--text-typography-t6)",
        /** Figma background tokens */
        "figma-bg-1": "var(--bg-1)",
        "figma-bg-2": "var(--bg-2)",
        "gray-2": "var(--gray-2)",
        /** UK flag mask fill (Figma asset chroma) */
        "flag-union": "var(--zulu-flag-union-blue)",
        /** Home landing section wash */
        "home-band": "var(--zulu-home-band)",
        "home-band-md": "var(--zulu-home-band-md)",
      },
      spacing: {
        /** Desktop header horizontal padding (120px) */
        header: "120px",
        /** 120px — logo / wide hit targets */
        30: "7.5rem",
        /** Language/currency dropdown width (180px) */
        45: "11.25rem",
      },
      zIndex: {
        "header-panel": "99",
        header: "100",
        dropdown: "140",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "ds-display-h1": [
          "var(--font-display-h1-size)",
          { lineHeight: "var(--font-display-h1-line-height)" },
        ],
        "ds-h1": ["var(--font-h1-size)", { lineHeight: "var(--font-h1-line-height)" }],
        "ds-h2": ["var(--font-h2-size)", { lineHeight: "var(--font-h2-line-height)" }],
        "ds-h3": ["var(--font-h3-size)", { lineHeight: "var(--font-h3-line-height)" }],
        "ds-h4": ["var(--font-h4-size)", { lineHeight: "var(--font-h4-line-height)" }],
        "ds-h5": ["var(--font-h5-size)", { lineHeight: "var(--font-h5-line-height)" }],
        "ds-h6": ["var(--font-h6-size)", { lineHeight: "var(--font-h6-line-height)" }],
        "ds-subtitle-1": [
          "var(--font-subtitle-1-size)",
          { lineHeight: "var(--font-subtitle-1-line-height)" },
        ],
        "ds-subtitle-2": [
          "var(--font-subtitle-2-size)",
          { lineHeight: "var(--font-subtitle-2-line-height)" },
        ],
        "ds-body-1": ["var(--font-body-1-size)", { lineHeight: "var(--font-body-1-line-height)" }],
        "ds-body-2": ["var(--font-body-2-size)", { lineHeight: "var(--font-body-2-line-height)" }],
        "ds-body-3": ["var(--font-body-3-size)", { lineHeight: "var(--font-body-3-line-height)" }],
        "ds-button-l": [
          "var(--font-button-l-size)",
          { lineHeight: "var(--font-button-l-line-height)" },
        ],
        "ds-button-m": [
          "var(--font-button-m-size)",
          { lineHeight: "var(--font-button-m-line-height)" },
        ],
        "ds-button-s": [
          "var(--font-button-s-size)",
          { lineHeight: "var(--font-button-s-line-height)" },
        ],
        "ds-caption": ["var(--font-caption-size)", { lineHeight: "var(--font-caption-line-height)" }],
        "ds-input-label": [
          "var(--font-input-label-size)",
          { lineHeight: "var(--font-input-label-line-height)" },
        ],
        "ds-input-text": [
          "var(--font-input-text-size)",
          { lineHeight: "var(--font-input-text-line-height)" },
        ],
        "ds-helper-text": [
          "var(--font-helper-text-size)",
          { lineHeight: "var(--font-helper-text-line-height)" },
        ],
        "ds-body-14": [
          "var(--font-body-14-regular-size)",
          { lineHeight: "var(--font-body-14-regular-line-height)" },
        ],
        "ds-caption-12": [
          "var(--font-caption-12-regular-size)",
          { lineHeight: "var(--font-caption-12-regular-line-height)" },
        ],
      },
      fontWeight: {
        "display-h1": "var(--font-display-h1-weight)",
        "ds-h1": "var(--font-h1-weight)",
        "ds-h2": "var(--font-h2-weight)",
        "ds-h3": "var(--font-h3-weight)",
        "ds-h4": "var(--font-h4-weight)",
        "ds-h5": "var(--font-h5-weight)",
        "ds-h6-semibold": "var(--font-h6-weight-semibold)",
        "ds-h6-medium": "var(--font-h6-weight-medium)",
        "ds-subtitle-1-medium": "var(--font-subtitle-1-weight-medium)",
        "ds-subtitle-1-semibold": "var(--font-subtitle-1-weight-semibold)",
        "ds-subtitle-2-medium": "var(--font-subtitle-2-weight-medium)",
        "ds-subtitle-2-semibold": "var(--font-subtitle-2-weight-semibold)",
        "ds-body-1-regular": "var(--font-body-1-weight-regular)",
        "ds-body-1-medium": "var(--font-body-1-weight-medium)",
        "ds-body-1-semibold": "var(--font-body-1-weight-semibold)",
        "ds-body-2-regular": "var(--font-body-2-weight-regular)",
        "ds-body-2-medium": "var(--font-body-2-weight-medium)",
        "ds-body-3-regular": "var(--font-body-3-weight-regular)",
        "ds-body-3-medium": "var(--font-body-3-weight-medium)",
        "ds-button-l": "var(--font-button-l-weight)",
        "ds-button-m": "var(--font-button-m-weight)",
        "ds-button-s": "var(--font-button-s-weight)",
        "ds-caption": "var(--font-caption-weight)",
        "ds-input-label": "var(--font-input-label-weight)",
        "ds-input-text": "var(--font-input-text-weight)",
        "ds-helper-text": "var(--font-helper-text-weight)",
      },
      borderRadius: {
        zulu: "8px",
        "zulu-card": "var(--radius-card)",
        "zulu-modal": "var(--radius-modal)",
      },
      boxShadow: {
        "zulu-card": "var(--shadow-card)",
        "zulu-modal": "var(--shadow-modal)",
        "zulu-dropdown": "var(--shadow-dropdown)",
      },
      maxWidth: {
        "zulu-modal": "600px",
        zulu: "var(--zulu-max-width)",
        /** Hero + home rails (1200px) */
        "zulu-content": "var(--zulu-home-content)",
      },
    },
  },
  plugins: [],
};
export default config;
